window.require = () => {};
const global = {};
import $, { event } from "jquery";
window.$ = window.jQuery = $;
import * as _ from "lodash";
window.lodash = _;
import Axios from "axios";
window.Axios = Axios;
import { Fancybox } from "@fancyapps/ui";
window.Fancybox = Fancybox;
import "@fancyapps/ui/dist/fancybox.css";
import moment from "moment";
window.moment = moment;
import Alpine from "alpinejs";
import mask from "@ryangjchandler/alpine-mask";
import plugin from "./alpine_plugin/plugin";
import form from "./alpine_plugin/form";
import dialog from "alpinjs-dialog";
Alpine.plugin(dialog);
Alpine.plugin(mask);
Alpine.plugin(plugin);
Alpine.plugin(form);
window.Alpine = Alpine;
import FormGroup from "./form-group";
window.FormGroup = FormGroup;
import Table from "./table";
window.Table = Table;
import * as feather from "feather-icons";
window.feather = feather;
import anime from "animejs/lib/anime.es.js";
window.anime = anime;
import daterangepicker from "daterangepicker";
window.daterangepicker = daterangepicker;
import onUploadFile from "./package/upload-file";
window.$onUploadFile = onUploadFile;
import Validator from "./package/validator";
window.$validatorOption = Validator;
require("./package/common");
import Collection from "s-collection.js";
window.Collection = Collection;
import { jsPDF } from "jspdf";
window.jsPDF = jsPDF;
require('./fonts/LexendDecaRegular-normal');
require('./package/iCheck/icheck.min');
